tal_cn_dict = {
 'a': 'a',
 'ar': 'a xer',
 'ai': 'ai',
 'air': 'ai xer',
 'an': 'an',
 'anr': 'an xer',
 'ang': 'ang',
 'angr': 'ang xer',
 'ao': 'ao',
 'aor': 'ao xer',
 'ba': 'b a',
 'bar': 'b a xer',
 'bai': 'b ai',
 'bair': 'b ai xer',
 'ban': 'b an',
 'banr': 'b an xer',
 'bang': 'b ang',
 'bangr': 'b ang xer',
 'bao': 'b ao',
 'baor': 'b ao xer',
 'bei': 'b ei',
 'beir': 'b ei xer',
 'ben': 'b en',
 'benr': 'b en xer',
 'beng': 'b eng',
 'bengr': 'b eng xer',
 'bi': 'b i',
 'bir': 'b i xer',
 'bian': 'b ian',
 'bianr': 'b ian xer',
 'biao': 'b iao',
 'biaor': 'b iao xer',
 'bie': 'b ie',
 'bier': 'b ie xer',
 'bin': 'b in',
 'binr': 'b in xer',
 'bing': 'b ing',
 'bingr': 'b ing xer',
 'bo': 'b o',
 'bor': 'b o xer',
 'bu': 'b u',
 'bur': 'b u xer',
 'ca': 'c a',
 'car': 'c a xer',
 'cai': 'c ai',
 'cair': 'c ai xer',
 'can': 'c an',
 'canr': 'c an xer',
 'cang': 'c ang',
 'cangr': 'c ang xer',
 'cao': 'c ao',
 'caor': 'c ao xer',
 'ce': 'c e',
 'cer': 'c e xer',
 'cen': 'c en',
 'cenr': 'c en xer',
 'ceng': 'c eng',
 'cengr': 'c eng xer',
 'cha': 'ch a',
 'char': 'ch a xer',
 'chai': 'ch ai',
 'chair': 'ch ai xer',
 'chan': 'ch an',
 'chanr': 'ch an xer',
 'chang': 'ch ang',
 'changr': 'ch ang xer',
 'chao': 'ch ao',
 'chaor': 'ch ao xer',
 'che': 'ch e',
 'cher': 'ch e xer',
 'chen': 'ch en',
 'chenr': 'ch en xer',
 'cheng': 'ch eng',
 'chengr': 'ch eng xer',
 'chi': 'ch iii',
 'chir': 'ch iii xer',
 'chong': 'ch ong',
 'chongr': 'ch ong xer',
 'chou': 'ch ou',
 'chour': 'ch ou xer',
 'chu': 'ch u',
 'chur': 'ch u xer',
 'chua': 'ch ua',
 'chuar': 'ch ua xer',
 'chuai': 'ch uai',
 'chuair': 'ch uai xer',
 'chuan': 'ch uan',
 'chuanr': 'ch uan xer',
 'chuang': 'ch uang',
 'chuangr': 'ch uang xer',
 'chui': 'ch uei',
 'chuir': 'ch uei xer',
 'chun': 'ch uen',
 'chunr': 'ch uen xer',
 'chuo': 'ch uo',
 'chuor': 'ch uo xer',
 'ci': 'c ii',
 'cir': 'c ii xer',
 'cong': 'c ong',
 'congr': 'c ong xer',
 'cou': 'c ou',
 'cour': 'c ou xer',
 'cu': 'c u',
 'cur': 'c u xer',
 'cuan': 'c uan',
 'cuanr': 'c uan xer',
 'cui': 'c uei',
 'cuir': 'c uei xer',
 'cun': 'c uen',
 'cunr': 'c uen xer',
 'cuo': 'c uo',
 'cuor': 'c uo xer',
 'da': 'd a',
 'dar': 'd a xer',
 'dai': 'd ai',
 'dair': 'd ai xer',
 'dan': 'd an',
 'danr': 'd an xer',
 'dang': 'd ang',
 'dangr': 'd ang xer',
 'dao': 'd ao',
 'daor': 'd ao xer',
 'de': 'd e',
 'der': 'd e xer',
 'dei': 'd ei',
 'deir': 'd ei xer',
 'den': 'd en',
 'denr': 'd en xer',
 'deng': 'd eng',
 'dengr': 'd eng xer',
 'di': 'd i',
 'dir': 'd i xer',
 'dia': 'd ia',
 'diar': 'd ia xer',
 'dian': 'd ian',
 'dianr': 'd ian xer',
 'diao': 'd iao',
 'diaor': 'd iao xer',
 'die': 'd ie',
 'dier': 'd ie xer',
 'ding': 'd ing',
 'dingr': 'd ing xer',
 'diu': 'd iou',
 'diur': 'd iou xer',
 'dong': 'd ong',
 'dongr': 'd ong xer',
 'dou': 'd ou',
 'dour': 'd ou xer',
 'du': 'd u',
 'dur': 'd u xer',
 'duan': 'd uan',
 'duanr': 'd uan xer',
 'dui': 'd uei',
 'duir': 'd uei xer',
 'dun': 'd uen',
 'dunr': 'd uen xer',
 'duo': 'd uo',
 'duor': 'd uo xer',
 'e': 'e',
 'ei': 'ei',
 'eir': 'ei xer',
 'en': 'en',
 'ng': 'en',
 'enr': 'en xer',
 'eng': 'eng',
 'engr': 'eng xer',
 'er': 'er',
 'fa': 'f a',
 'far': 'f a xer',
 'fai': 'f ai',
 'fair': 'f ai xer',
 'fan': 'f an',
 'fanr': 'f an xer',
 'fang': 'f ang',
 'fangr': 'f ang xer',
 'fei': 'f ei',
 'feir': 'f ei xer',
 'fen': 'f en',
 'fenr': 'f en xer',
 'feng': 'f eng',
 'fengr': 'f eng xer',
 'fiao': 'f iao',
 'fiaor': 'f iao xer',
 'fo': 'f o',
 'for': 'f o xer',
 'fou': 'f ou',
 'four': 'f ou xer',
 'fu': 'f u',
 'fur': 'f u xer',
 'ga': 'g a',
 'gar': 'g a xer',
 'gai': 'g ai',
 'gair': 'g ai xer',
 'gan': 'g an',
 'ganr': 'g an xer',
 'gang': 'g ang',
 'gangr': 'g ang xer',
 'gao': 'g ao',
 'gaor': 'g ao xer',
 'ge': 'g e',
 'ger': 'g e xer',
 'gei': 'g ei',
 'geir': 'g ei xer',
 'gen': 'g en',
 'genr': 'g en xer',
 'geng': 'g eng',
 'gengr': 'g eng xer',
 'gong': 'g ong',
 'gongr': 'g ong xer',
 'gou': 'g ou',
 'gour': 'g ou xer',
 'gu': 'g u',
 'gur': 'g u xer',
 'gua': 'g ua',
 'guar': 'g ua xer',
 'guai': 'g uai',
 'guair': 'g uai xer',
 'guan': 'g uan',
 'guanr': 'g uan xer',
 'guang': 'g uang',
 'guangr': 'g uang xer',
 'gui': 'g uei',
 'guir': 'g uei xer',
 'gun': 'g uen',
 'gunr': 'g uen xer',
 'guo': 'g uo',
 'guor': 'g uo xer',
 'ha': 'h a',
 'har': 'h a xer',
 'hai': 'h ai',
 'hair': 'h ai xer',
 'han': 'h an',
 'hanr': 'h an xer',
 'hang': 'h ang',
 'hangr': 'h ang xer',
 'hao': 'h ao',
 'haor': 'h ao xer',
 'he': 'h e',
 'her': 'h e xer',
 'hei': 'h ei',
 'heir': 'h ei xer',
 'hen': 'h en',
 'henr': 'h en xer',
 'heng': 'h eng',
 'hengr': 'h eng xer',
 'hong': 'h ong',
 'hongr': 'h ong xer',
 'hou': 'h ou',
 'hour': 'h ou xer',
 'hu': 'h u',
 'hur': 'h u xer',
 'hua': 'h ua',
 'huar': 'h ua xer',
 'huai': 'h uai',
 'huair': 'h uai xer',
 'huan': 'h uan',
 'huanr': 'h uan xer',
 'huang': 'h uang',
 'huangr': 'h uang xer',
 'hui': 'h uei',
 'huir': 'h uei xer',
 'hun': 'h uen',
 'hunr': 'h uen xer',
 'huo': 'h uo',
 'huor': 'h uo xer',
 'ji': 'j i',
 'jir': 'j i xer',
 'jia': 'j ia',
 'jiar': 'j ia xer',
 'jian': 'j ian',
 'jianr': 'j ian xer',
 'jiang': 'j iang',
 'jiangr': 'j iang xer',
 'jiao': 'j iao',
 'jiaor': 'j iao xer',
 'jie': 'j ie',
 'jier': 'j ie xer',
 'jin': 'j in',
 'jinr': 'j in xer',
 'jing': 'j ing',
 'jingr': 'j ing xer',
 'jiong': 'j iong',
 'jiongr': 'j iong xer',
 'jiu': 'j iou',
 'jiur': 'j iou xer',
 'ju': 'j v',
 'jur': 'j v xer',
 'jv': 'j v',
 'jvr': 'j v xer',
 'juan': 'j van',
 'juanr': 'j van xer',
 'jvan': 'j van',
 'jvanr': 'j van xer',
 'jue': 'j ve',
 'juer': 'j ve xer',
 'jve': 'j ve',
 'jver': 'j ve xer',
 'jun': 'j vn',
 'junr': 'j vn xer',
 'jvn': 'j vn',
 'jvnr': 'j vn xer',
 'ka': 'k a',
 'kar': 'k a xer',
 'kai': 'k ai',
 'kair': 'k ai xer',
 'kan': 'k an',
 'kanr': 'k an xer',
 'kang': 'k ang',
 'kangr': 'k ang xer',
 'kao': 'k ao',
 'kaor': 'k ao xer',
 'ke': 'k e',
 'ker': 'k e xer',
 'kei': 'k ei',
 'keir': 'k ei xer',
 'ken': 'k en',
 'kenr': 'k en xer',
 'keng': 'k eng',
 'kengr': 'k eng xer',
 'kiu': 'k iou',
 'kiur': 'k iou xer',
 'kong': 'k ong',
 'kongr': 'k ong xer',
 'kou': 'k ou',
 'kour': 'k ou xer',
 'ku': 'k u',
 'kur': 'k u xer',
 'kua': 'k ua',
 'kuar': 'k ua xer',
 'kuai': 'k uai',
 'kuair': 'k uai xer',
 'kuan': 'k uan',
 'kuanr': 'k uan xer',
 'kuang': 'k uang',
 'kuangr': 'k uang xer',
 'kui': 'k uei',
 'kuir': 'k uei xer',
 'kun': 'k uen',
 'kunr': 'k uen xer',
 'kuo': 'k uo',
 'kuor': 'k uo xer',
 'la': 'l a',
 'lar': 'l a xer',
 'lai': 'l ai',
 'lair': 'l ai xer',
 'lan': 'l an',
 'lanr': 'l an xer',
 'lang': 'l ang',
 'langr': 'l ang xer',
 'lao': 'l ao',
 'laor': 'l ao xer',
 'le': 'l e',
 'ler': 'l e xer',
 'lei': 'l ei',
 'leir': 'l ei xer',
 'leng': 'l eng',
 'lengr': 'l eng xer',
 'li': 'l i',
 'lir': 'l i xer',
 'lia': 'l ia',
 'liar': 'l ia xer',
 'lian': 'l ian',
 'lianr': 'l ian xer',
 'liang': 'l iang',
 'liangr': 'l iang xer',
 'liao': 'l iao',
 'liaor': 'l iao xer',
 'lie': 'l ie',
 'lier': 'l ie xer',
 'lin': 'l in',
 'linr': 'l in xer',
 'ling': 'l ing',
 'lingr': 'l ing xer',
 'liu': 'l iou',
 'liur': 'l iou xer',
 'lo': 'l o',
 'lor': 'l o xer',
 'long': 'l ong',
 'longr': 'l ong xer',
 'lou': 'l ou',
 'lour': 'l ou xer',
 'lu': 'l u',
 'lur': 'l u xer',
 'lv': 'l v',
 'lvr': 'l v xer',
 'luan': 'l uan',
 'luanr': 'l uan xer',
 'lve': 'l ve',
 'lver': 'l ve xer',
 'lun': 'l uen',
 'lunr': 'l uen xer',
 'luo': 'l uo',
 'luor': 'l uo xer',
 'ma': 'm a',
 'mar': 'm a xer',
 'mai': 'm ai',
 'mair': 'm ai xer',
 'man': 'm an',
 'manr': 'm an xer',
 'mang': 'm ang',
 'mangr': 'm ang xer',
 'mao': 'm ao',
 'maor': 'm ao xer',
 'me': 'm e',
 'mer': 'm e xer',
 'mei': 'm ei',
 'meir': 'm ei xer',
 'men': 'm en',
 'menr': 'm en xer',
 'meng': 'm eng',
 'mengr': 'm eng xer',
 'mi': 'm i',
 'mir': 'm i xer',
 'mian': 'm ian',
 'mianr': 'm ian xer',
 'miao': 'm iao',
 'miaor': 'm iao xer',
 'mie': 'm ie',
 'mier': 'm ie xer',
 'min': 'm in',
 'minr': 'm in xer',
 'ming': 'm ing',
 'mingr': 'm ing xer',
 'miu': 'm iou',
 'miur': 'm iou xer',
 'mo': 'm o',
 'mor': 'm o xer',
 'mou': 'm ou',
 'mour': 'm ou xer',
 'mu': 'm u',
 'mur': 'm u xer',
 'na': 'n a',
 'nar': 'n a xer',
 'nai': 'n ai',
 'nair': 'n ai xer',
 'nan': 'n an',
 'nanr': 'n an xer',
 'nang': 'n ang',
 'nangr': 'n ang xer',
 'nao': 'n ao',
 'naor': 'n ao xer',
 'ne': 'n e',
 'ner': 'n e xer',
 'nei': 'n ei',
 'neir': 'n ei xer',
 'nen': 'n en',
 'nenr': 'n en xer',
 'neng': 'n eng',
 'nengr': 'n eng xer',
 'ni': 'n i',
 'nir': 'n i xer',
 'nia': 'n ia',
 'niar': 'n ia xer',
 'nian': 'n ian',
 'nianr': 'n ian xer',
 'niang': 'n iang',
 'niangr': 'n iang xer',
 'niao': 'n iao',
 'niaor': 'n iao xer',
 'nie': 'n ie',
 'nier': 'n ie xer',
 'nin': 'n in',
 'ninr': 'n in xer',
 'ning': 'n ing',
 'ningr': 'n ing xer',
 'niu': 'n iou',
 'niur': 'n iou xer',
 'nong': 'n ong',
 'nongr': 'n ong xer',
 'nou': 'n ou',
 'nour': 'n ou xer',
 'nu': 'n u',
 'nur': 'n u xer',
 'nv': 'n v',
 'nvr': 'n v xer',
 'nuan': 'n uan',
 'nuanr': 'n uan xer',
 'nve': 'n ve',
 'nver': 'n ve xer',
 'nuo': 'n uo',
 'nuor': 'n uo xer',
 'o': 'o',
 'or': 'o xer',
 'ou': 'ou',
 'our': 'ou xer',
 'pa': 'p a',
 'par': 'p a xer',
 'pai': 'p ai',
 'pair': 'p ai xer',
 'pan': 'p an',
 'panr': 'p an xer',
 'pang': 'p ang',
 'pangr': 'p ang xer',
 'pao': 'p ao',
 'paor': 'p ao xer',
 'pei': 'p ei',
 'peir': 'p ei xer',
 'pen': 'p en',
 'penr': 'p en xer',
 'peng': 'p eng',
 'pengr': 'p eng xer',
 'pi': 'p i',
 'pir': 'p i xer',
 'pian': 'p ian',
 'pianr': 'p ian xer',
 'piao': 'p iao',
 'piaor': 'p iao xer',
 'pie': 'p ie',
 'pier': 'p ie xer',
 'pin': 'p in',
 'pinr': 'p in xer',
 'ping': 'p ing',
 'pingr': 'p ing xer',
 'po': 'p o',
 'por': 'p o xer',
 'pou': 'p ou',
 'pour': 'p ou xer',
 'pu': 'p u',
 'pur': 'p u xer',
 'qi': 'q i',
 'qir': 'q i xer',
 'qia': 'q ia',
 'qiar': 'q ia xer',
 'qian': 'q ian',
 'qianr': 'q ian xer',
 'qiang': 'q iang',
 'qiangr': 'q iang xer',
 'qiao': 'q iao',
 'qiaor': 'q iao xer',
 'qie': 'q ie',
 'qier': 'q ie xer',
 'qin': 'q in',
 'qinr': 'q in xer',
 'qing': 'q ing',
 'qingr': 'q ing xer',
 'qiong': 'q iong',
 'qiongr': 'q iong xer',
 'qiu': 'q iou',
 'qiur': 'q iou xer',
 'qu': 'q v',
 'qur': 'q v xer',
 'qv': 'q v',
 'qvr': 'q v xer',
 'quan': 'q van',
 'qvan': 'q van',
 'quanr': 'q van xer',
 'qvanr': 'q van xer',
 'que': 'q ve',
 'quer': 'q ve xer',
 'qve': 'q ve',
 'qver': 'q ve xer',
 'qun': 'q vn',
 'qunr': 'q vn xer',
 'qvn': 'q vn',
 'qvnr': 'q vn xer',
 'ran': 'r an',
 'ranr': 'r an xer',
 'rang': 'r ang',
 'rangr': 'r ang xer',
 'rao': 'r ao',
 'raor': 'r ao xer',
 're': 'r e',
 'rer': 'r e xer',
 'ren': 'r en',
 'renr': 'r en xer',
 'reng': 'r eng',
 'rengr': 'r eng xer',
 'ri': 'r iii',
 'rir': 'r iii xer',
 'rong': 'r ong',
 'rongr': 'r ong xer',
 'rou': 'r ou',
 'rour': 'r ou xer',
 'ru': 'r u',
 'rur': 'r u xer',
 'rua': 'r ua',
 'ruar': 'r ua xer',
 'ruan': 'r uan',
 'ruanr': 'r uan xer',
 'rui': 'r uei',
 'ruir': 'r uei xer',
 'run': 'r uen',
 'runr': 'r uen xer',
 'ruo': 'r uo',
 'ruor': 'r uo xer',
 'sa': 's a',
 'sar': 's a xer',
 'sai': 's ai',
 'sair': 's ai xer',
 'san': 's an',
 'sanr': 's an xer',
 'sang': 's ang',
 'sangr': 's ang xer',
 'sao': 's ao',
 'saor': 's ao xer',
 'se': 's e',
 'ser': 's e xer',
 'sei': 's ei',
 'seir': 's ei xer',
 'sen': 's en',
 'senr': 's en xer',
 'seng': 's eng',
 'sengr': 's eng xer',
 'sha': 'sh a',
 'shar': 'sh a xer',
 'shai': 'sh ai',
 'shair': 'sh ai xer',
 'shan': 'sh an',
 'shanr': 'sh an xer',
 'shang': 'sh ang',
 'shangr': 'sh ang xer',
 'shao': 'sh ao',
 'shaor': 'sh ao xer',
 'she': 'sh e',
 'sher': 'sh e xer',
 'shei': 'sh ei',
 'sheir': 'sh ei xer',
 'shen': 'sh en',
 'shenr': 'sh en xer',
 'sheng': 'sh eng',
 'shengr': 'sh eng xer',
 'shi': 'sh iii',
 'shir': 'sh iii xer',
 'shou': 'sh ou',
 'shour': 'sh ou xer',
 'shu': 'sh u',
 'shur': 'sh u xer',
 'shua': 'sh ua',
 'shuar': 'sh ua xer',
 'shuai': 'sh uai',
 'shuair': 'sh uai xer',
 'shuan': 'sh uan',
 'shuanr': 'sh uan xer',
 'shuang': 'sh uang',
 'shuangr': 'sh uang xer',
 'shui': 'sh uei',
 'shuir': 'sh uei xer',
 'shun': 'sh uen',
 'shunr': 'sh uen xer',
 'shuo': 'sh uo',
 'shuor': 'sh uo xer',
 'si': 's ii',
 'sir': 's ii xer',
 'song': 's ong',
 'songr': 's ong xer',
 'sou': 's ou',
 'sour': 's ou xer',
 'su': 's u',
 'sur': 's u xer',
 'suan': 's uan',
 'suanr': 's uan xer',
 'sui': 's uei',
 'suir': 's uei xer',
 'sun': 's uen',
 'sunr': 's uen xer',
 'suo': 's uo',
 'suor': 's uo xer',
 'ta': 't a',
 'tar': 't a xer',
 'tai': 't ai',
 'tair': 't ai xer',
 'tan': 't an',
 'tanr': 't an xer',
 'tang': 't ang',
 'tangr': 't ang xer',
 'tao': 't ao',
 'taor': 't ao xer',
 'te': 't e',
 'ter': 't e xer',
 'tei': 't ei',
 'teir': 't ei xer',
 'teng': 't eng',
 'tengr': 't eng xer',
 'ti': 't i',
 'tir': 't i xer',
 'tian': 't ian',
 'tianr': 't ian xer',
 'tiao': 't iao',
 'tiaor': 't iao xer',
 'tie': 't ie',
 'tier': 't ie xer',
 'ting': 't ing',
 'tingr': 't ing xer',
 'tong': 't ong',
 'tongr': 't ong xer',
 'tou': 't ou',
 'tour': 't ou xer',
 'tu': 't u',
 'tur': 't u xer',
 'tuan': 't uan',
 'tuanr': 't uan xer',
 'tui': 't uei',
 'tuir': 't uei xer',
 'tun': 't uen',
 'tunr': 't uen xer',
 'tuo': 't uo',
 'tuor': 't uo xer',
 'wa': 'ua',
 'war': 'ua xer',
 'wai': 'uai',
 'wair': 'uai xer',
 'wan': 'uan',
 'wanr': 'uan xer',
 'wang': 'uang',
 'wangr': 'uang xer',
 'wei': 'uei',
 'weir': 'uei xer',
 'wen': 'uen',
 'wenr': 'uen xer',
 'weng': 'ueng',
 'wengr': 'ueng xer',
 'wo': 'uo',
 'wor': 'uo xer',
 'wu': 'u',
 'wur': 'u xer',
 'xi': 'x i',
 'xir': 'x i xer',
 'xia': 'x ia',
 'xiar': 'x ia xer',
 'xian': 'x ian',
 'xianr': 'x ian xer',
 'xiang': 'x iang',
 'xiangr': 'x iang xer',
 'xiao': 'x iao',
 'xiaor': 'x iao xer',
 'xie': 'x ie',
 'xier': 'x ie xer',
 'xin': 'x in',
 'xinr': 'x in xer',
 'xing': 'x ing',
 'xingr': 'x ing xer',
 'xiong': 'x iong',
 'xiongr': 'x iong xer',
 'xiu': 'x iou',
 'xiur': 'x iou xer',
 'xu': 'x v',
 'xur': 'x v xer',
 'xv': 'x v',
 'xvr': 'x v xer',
 'xuan': 'x van',
 'xuanr': 'x van xer',
 'xvan': 'x van',
 'xvanr': 'x van xer',
 'xue': 'x ve',
 'xuer': 'x ve xer',
 'xve': 'x ve',
 'xver': 'x ve xer',
 'xun': 'x vn',
 'xunr': 'x vn xer',
 'xvn': 'x vn',
 'xvnr': 'x vn xer',
 'ya': 'ia',
 'yar': 'ia xer',
 'yan': 'ian',
 'yanr': 'ian xer',
 'yang': 'iang',
 'yangr': 'iang xer',
 'yao': 'iao',
 'yaor': 'iao xer',
 'ye': 'ie',
 'yer': 'ie xer',
 'yi': 'i',
 'yir': 'i xer',
 'yin': 'in',
 'yinr': 'in xer',
 'ying': 'ing',
 'yingr': 'ing xer',
 'yo': 'io',
 'yor': 'o xer',
 'yong': 'iong',
 'yongr': 'iong xer',
 'you': 'iou',
 'your': 'iou xer',
 'yu': 'v',
 'yv': 'v',
 'yur': 'v xer',
 'yvr': 'v xer',
 'yuan': 'van',
 'yuanr': 'van xer',
 'yvan': 'van',
 'yvanr': 'van xer',
 'yue': 've',
 'yve': 've',
 'yuer': 've xer',
 'yver': 've xer',
 'yun': 'vn',
 'yvn': 'vn',
 'yunr': 'vn xer',
 'yvnr': 'vn xer',
 'za': 'z a',
 'zar': 'z a xer',
 'zai': 'z ai',
 'zair': 'z ai xer',
 'zan': 'z an',
 'zanr': 'z an xer',
 'zang': 'z ang',
 'zangr': 'z ang xer',
 'zao': 'z ao',
 'zaor': 'z ao xer',
 'ze': 'z e',
 'zer': 'z e xer',
 'zei': 'z ei',
 'zeir': 'z ei xer',
 'zen': 'z en',
 'zenr': 'z en xer',
 'zeng': 'z eng',
 'zengr': 'z eng xer',
 'zha': 'zh a',
 'zhar': 'zh a xer',
 'zhai': 'zh ai',
 'zhair': 'zh ai xer',
 'zhan': 'zh an',
 'zhanr': 'zh an xer',
 'zhang': 'zh ang',
 'zhangr': 'zh ang xer',
 'zhao': 'zh ao',
 'zhaor': 'zh ao xer',
 'zhe': 'zh e',
 'zher': 'zh e xer',
 'zhei': 'zh ei',
 'zheir': 'zh ei xer',
 'zhen': 'zh en',
 'zhenr': 'zh en xer',
 'zheng': 'zh eng',
 'zhengr': 'zh eng xer',
 'zhi': 'zh iii',
 'zhir': 'zh iii xer',
 'zhong': 'zh ong',
 'zhongr': 'zh ong xer',
 'zhou': 'zh ou',
 'zhour': 'zh ou xer',
 'zhu': 'zh u',
 'zhur': 'zh u xer',
 'zhua': 'zh ua',
 'zhuar': 'zh ua xer',
 'zhuai': 'zh uai',
 'zhuair': 'zh uai xer',
 'zhuan': 'zh uan',
 'zhuanr': 'zh uan xer',
 'zhuang': 'zh uang',
 'zhuangr': 'zh uang xer',
 'zhui': 'zh uei',
 'zhuir': 'zh uei xer',
 'zhun': 'zh uen',
 'zhunr': 'zh uen xer',
 'zhuo': 'zh uo',
 'zhuor': 'zh uo xer',
 'zi': 'z ii',
 'zir': 'z ii xer',
 'zong': 'z ong',
 'zongr': 'z ong xer',
 'zou': 'z ou',
 'zour': 'z ou xer',
 'zu': 'z u',
 'zur': 'z u xer',
 'zuan': 'z uan',
 'zuanr': 'z uan xer',
 'zui': 'z uei',
 'zuir': 'z uei xer',
 'zun': 'z uen',
 'zunr': 'z uen xer',
 'zuo': 'z uo',
 'zuor': 'z uo xer',
 }
