project: tal_frontend
version: 1.0.0


# llm_url: http://hmi.chengjiukehu.com/g2p-pp-service
tts_triton_url: 47.94.0.184:8000
formular2text_url: http://123.57.25.89:8023/inference
# g2p_url: 112.126.23.219:80
# pp_url: 123.56.235.205:80
g2p_pp_url: 123.56.235.205:80
g2ppp_model_name: vits_rhy_704

senlen: 30
en_phoneme_ave_len: 6

bert_model_path: /mnt/cfs/NLP/hub_models/bert-base-multilingual-cased       

en_monophone_file: tal_frontend/frontend/g2p/bertg2pw/english_dict.list
polyphonic_chars_path: tal_frontend/frontend/g2p_pp/POLYPHONIC_CHARS_704.txt

en_monophone_file: tal_frontend/frontend/g2p/bertg2pw/english_dict.list

# redis

host: r-2ze7sx5pe00o4w0mer.redis.rds.aliyuncs.com
password: DySfiNWD9Ilwa91_
port: 6379