project: tal_frontend
version: 1.0.0

llm_url: http://hmi.chengjiukehu.com/g2p-pp-service
tts_triton_url: 47.94.0.184:8000
formular2text_url: http://123.57.25.89:8023/inference


project: tal_frontend
version: 1.0.0

llm_url: http://hmi.chengjiukehu.com/g2p-pp-service
tts_triton_url: tal-vits-triton-backend-lb.monkey-correction-ai:8000
# formular2text_url: http://hmi.chengjiukehu.com/tal-vits-formluar2text
formular2text_url: http://vits-formula2text-svc.aielearning-hmi-golang:80/inference 

project: tal_frontend
version: 1.0.0

tts_triton_url: tal-vits-triton-backend-lb.monkey-correction-ai:8000
formular2text_url: vits-formula2text-svc.aielearning-hmi-golang:80/inference 
g2p_pp_url: tal-vits-rhythm-triton.aielearning-hmi-golang:8000

senlen: 30
en_phoneme_ave_len: 6
